### ISSUE TITLE
readme should indicate to change the wallet path in `Anchor.toml`

### ISSUE THREAD

**Issue by bonedaddy** [armaniferrante/serum-quickstart#3]
With the defaults in `Anchor.toml` it points to a wallet path for your home directory and attempting to run `anchor test` will fail with the following errror

```
Error: Unable to read keypair file
```

The readme should indicate that you will need to update the `wallet` setting to point to an `id.json` that exists on your machine.

**Comment by armaniferrante** [comment]
Anchor.toml now uses `~/.config/solana/id.json` as the default path and the readme has a note on changing the path. Closing.
